---
title: "paper-graphs"
author: "Lukáš 'hejtmy' Hejtmánek"
date: "12/12/2019"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(papaja)

source("../Scripts/paper-prepare.R")
source("../TwoWorlds/helpers-report.R")

#settings <- load_google_sheets()
load('../settings.data')

#green, violet, blue, yellow, pink, dark blue
estimote_pal <- c('#b6d6c1', '#54003d','#93d5f6','#d5d215','#f3aacb','#2d2556')
theme_set(theme_minimal() + 
          theme(axis.text=element_text(size=14),
                axis.title=element_text(size=16),
                axis.title.y = element_text(size=20),
                strip.text.x = element_text(size=20),
                plot.subtitle = element_text(hjust = 1, vjust = 0, size = 18, face = "italic"))
          )

### Try running it without outliers
sub_walk_all[!is.na(sub_walk_all$norm_distance) & sub_walk_all$norm_distance > 3, c("distance", "min_norm_distance")] <- NA
walk_all[!is.na(walk_all$norm_distance) & walk_all$norm_distance > 3, c("distance", "min_norm_distance")] <- NA

sub_walk_all_factor <- sub_walk_all
sub_walk_all_factor$exp_block_id <- factor(sub_walk_all_factor$exp_block_id)
sub_walk_all_factor$id <- factor(sub_walk_all_factor$id)
sub_walk_all_factor$learning.condition <- factor(sub_walk_all_factor$learning.condition)

point_data_1 <- sub_sop_all[sub_sop_all$phase == 1,]
knitr::opts_chunk$set(echo=F, warning = F, message = F)
```


## 5a
```{r, fig.width=10, fig.height=8}
ggplot(only_blocks(sub_walk_all_factor, 1:3), aes(x = graph.exp_block_id, y = errors, fill = graph.exp_block_id)) +
  stat_summary(fun.y=mean,position=position_dodge(width=0.95), geom="bar") +
  stat_summary(fun.data=mean_se, position=position_dodge(0.95), geom="errorbar", width = 0.2, size = 1.25) + 
  facet_wrap(~graph.learning.condition, strip.position = "bottom", scales = "free_x") + 
  scale_fill_manual(values=estimote_pal,"Block") + guides(fill=F) +
  labs(x = NULL, y ="Average number of visitation errors", subtitle = "5a") +
  theme(panel.spacing = unit(0, "lines"), 
         strip.background = element_blank(),
         strip.placement = "outside")
```


## 5b
```{r, fig.width=10, fig.height=8}
# Pre transfer plot of normalised distances
ggplot(only_blocks(sub_walk_all_factor, 1:3), aes(x = graph.exp_block_id, y = min_norm_distance, fill = graph.exp_block_id)) +
  stat_summary(fun.y=mean,position=position_dodge(width=0.95), geom="bar") +
  stat_summary(fun.data=mean_se, position=position_dodge(0.95), geom="errorbar", width = 0.2, size = 1.25) + 
  facet_wrap(~graph.learning.condition, strip.position = "bottom", scales = "free_x") + 
  scale_fill_manual(values=estimote_pal,"Block") + 
  labs(x = NULL, y = "Average normalised trial distance", subtitle = "5b") +
  guides(fill=F) +
  theme(panel.spacing = unit(0, "lines"), 
         strip.background = element_blank(),
         strip.placement = "outside")
```

## 5c

```{r, fig.width=10, fig.height=8}
ggplot(point_data_1, aes(x = graph.learning.condition, y = abs_error, fill = graph.learning.condition)) +
  stat_summary(fun.y=mean, position=position_dodge(width=0.95), geom="bar") +
  stat_summary(fun.data=mean_se, position=position_dodge(0.95), geom="errorbar", width = 0.2, size = 1.25) + 
  scale_fill_manual(values = estimote_pal, "Learning condition") +
  labs(x = NULL, y = "Average pointing error after learning phase", subtitle = "5c") +
  guides(fill=F) + 
  theme(axis.text.x = element_text(size=18, color= "black"))
```

## 6a

```{r, fig.width=10, fig.height=8}
ggplot(only_blocks(sub_walk_all_factor, 3:4), aes(x = graph.exp_block_id, y = errors, fill = graph.exp_block_id)) +
  stat_summary(fun.y = mean,position=position_dodge(width = 0.95),geom="bar") +
  stat_summary(fun.data = mean_se, position = position_dodge(0.95), geom="errorbar", width = 0.2, size = 1.25) + 
  scale_fill_manual(values = estimote_pal,"Block") + 
  facet_wrap(~graph.learning.condition, strip.position = "bottom", scales = "free_x") + 
  labs(x=NULL, y = "Average number of visitation errors", subtitle = "6a") +
  guides(fill = F) +
  theme(panel.spacing = unit(0, "lines"), 
        strip.background = element_blank(),
        strip.placement = "outside")
```

## 6b
```{r, fig.width=10, fig.height=8}
### graphs
ggplot(only_blocks(sub_walk_all_factor, 3:4), aes(x = graph.exp_block_id, y = min_norm_distance, fill = graph.exp_block_id)) +
  stat_summary(fun.y=mean,position=position_dodge(width=0.95),geom="bar") +
  stat_summary(fun.data=mean_se, position=position_dodge(0.95), geom="errorbar", width = 0.2, size = 1.25) + 
  scale_fill_manual(values=estimote_pal,"Block") + 
  facet_wrap(~graph.learning.condition, strip.position = "bottom", scales = "free_x") + 
  labs(x= NULL, y = "Average normalised trial distance", subtitle = "6b") +
  guides(fill = F) +
  theme(panel.spacing = unit(0, "lines"), 
         strip.background = element_blank(),
         strip.placement = "outside")
```

## 7a

```{r, fig.width=10, fig.height=8}
only_blocks(walk_all, 6) %>%
  select(testing.condition, min_norm_distance, graph.learning.condition) %>%
  rbind(data.frame(testing.condition = "Immersive VR", graph.learning.condition="Desktop", min_norm_distance = NA)) %>%
  ggplot(aes(x = testing.condition, y = min_norm_distance, fill = testing.condition)) +
  stat_summary(fun.y=mean,position=position_dodge(width=0.95),geom="bar") +
  stat_summary(fun.data=mean_se, position=position_dodge(0.95), geom="errorbar", width = 0.2, size = 1.25) + 
  scale_fill_manual(values = estimote_pal, "Transfer condition") +
  facet_wrap(~graph.learning.condition, strip.position = "bottom", scales = "free_x") +
  labs(x = NULL, y = "Average path distance in the last\n block of the transfer phase", subtitle = "7a") + 
  theme(panel.spacing = unit(0, "lines"),
        strip.background = element_blank(),
        strip.placement = "outside",
        legend.position = "top",
        legend.title = element_text(size = 16),
        legend.text = element_text(size = 16),
        axis.text.x = element_blank(),
        strip.text = element_text(size = 16),
        plot.title = element_text(hjust = 0.5))
```

## 7b

```{r, fig.width=10, fig.height=8}
only_blocks(walk_all, 6) %>%
  select(testing.condition, errors, graph.learning.condition) %>%
  rbind(data.frame(testing.condition = "Immersive VR", graph.learning.condition="Desktop", errors = NA)) %>% 
  ggplot(aes(x = testing.condition, y = errors, fill = testing.condition)) +
  stat_summary(fun.y = mean, position = position_dodge(width=0.95), geom = "bar") +
  stat_summary(fun.data = mean_se, position=position_dodge(0.95), geom="errorbar", width = 0.2, size = 1.25) +
  facet_wrap(~graph.learning.condition, strip.position = "bottom", scales = "free_x") +
  scale_fill_manual(values = estimote_pal, "Transfer condition") +
  labs(x = NULL, y = "Average number of visitation errors in\n the last block of the transfer phase", subtitle = "7b") +
  theme(panel.spacing = unit(0, "lines"),
        strip.background = element_blank(),
        strip.placement = "outside",
        legend.position = "top",
        legend.title = element_text(size = 16),
        legend.text = element_text(size = 16),
        axis.text.x = element_blank(),
        strip.text = element_text(size = 16),
        plot.title = element_text(hjust = 0.5))
```
