---
title: "Progress report"
author: "Lukáš 'hejtmy' Hejtmánek"
date: "3 May 2018"
output: html_document
---

```{r setup, include=FALSE}
library(ggplot2)
library(dplyr)
library(restimoter)
library(navr)
library(brainvr.R)
source_folder <- function(path){
  sapply(list.files(pattern = "[.]R$", path = path, full.names = TRUE), source);
}
source_folder("../TwoWorlds/")

sop_all <- read.table("../sop.csv", sep=";", header = T, stringsAsFactors = F)
walk_all <- read.table("../walk.csv", sep=";", header = T, stringsAsFactors = F)
walk_smoothed <- read.table("../walk_smoothed.csv", sep=";", header = T, stringsAsFactors = F)
```

Distance absolute - in Unity units and in meteds

```{r, echo = F,warning=FALSE}
ggplot(walk_all, aes(x = condition, y = distance, fill=factor(phase))) +
  stat_summary(fun.data=mean_cl_normal,position=position_dodge(0.95),geom="errorbar") + 
  stat_summary(fun.y=mean,position=position_dodge(width=0.95),geom="bar")
```

Distance smoothed absolute

```{r, echo = F,warning=FALSE}
ggplot(walk_smoothed, aes(x = condition, y = distance, fill=factor(phase))) +
  stat_summary(fun.data=mean_cl_normal,position=position_dodge(0.95),geom="errorbar") + 
  stat_summary(fun.y=mean,position=position_dodge(width=0.95),geom="bar")
```

Distance normalised

```{r, echo = F, warning=FALSE}
ggplot(walk_all, aes(x = condition, y = min_norm_distance, fill=factor(phase))) +
  stat_summary(fun.data=mean_cl_normal,position=position_dodge(0.95),geom="errorbar") + 
  stat_summary(fun.y=mean,position=position_dodge(width=0.95),geom="bar")
```

Normalised smoothed distance

```{r, echo = F, warning=FALSE}
ggplot(walk_smoothed, aes(x = condition, y = min_norm_distance, fill=factor(phase))) +
  stat_summary(fun.data=mean_cl_normal,position=position_dodge(0.95),geom="errorbar") + 
  stat_summary(fun.y=mean,position=position_dodge(width=0.95),geom="bar")
```

# Per block stats
Condition changes in the 4th block (1-3 1st condtition, 4-6th second condition.) In case of low transfer, we should expect an upward peak in the 4th block

```{r, echo = F,warning=FALSE}
ggplot(walk_all, aes(x = condition, y = distance, fill=factor(exp_block_id))) +
  stat_summary(fun.data=mean_cl_normal,position=position_dodge(0.95),geom="errorbar") + 
  stat_summary(fun.y=mean,position=position_dodge(width=0.95),geom="bar") + ggtitle("Absolute distance")
```

```{r, echo = F,warning=FALSE}
ggplot(walk_smoothed, aes(x = condition, y = distance, fill=factor(exp_block_id))) +
  stat_summary(fun.data=mean_cl_normal,position=position_dodge(0.95),geom="errorbar") + 
  stat_summary(fun.y=mean,position=position_dodge(width=0.95),geom="bar") + ggtitle("Absolute distance - smoothed")
```

```{r, echo = F,warning=FALSE}
ggplot(walk_all, aes(x = condition, y = min_norm_distance, fill=factor(exp_block_id))) +
  stat_summary(fun.data=mean_cl_normal,position=position_dodge(0.95),geom="errorbar") + 
  stat_summary(fun.y=mean,position=position_dodge(width=0.95),geom="bar")+ ggtitle("Normalised distance to the goal per block")
```

```{r, echo = F,warning=FALSE}
ggplot(walk_smoothed, aes(x = condition, y = min_norm_distance, fill=factor(exp_block_id))) +
  stat_summary(fun.data=mean_cl_normal,position=position_dodge(0.95),geom="errorbar") + 
  stat_summary(fun.y=mean,position=position_dodge(width=0.95),geom="bar")+ ggtitle("Normalised distance to the goal per block - smoothed")
```

```{r, echo = F,warning=FALSE}
ggplot(walk_all, aes(x = condition, y = errors, fill=factor(exp_block_id))) +
  stat_summary(fun.data=mean_cl_normal,position=position_dodge(0.95),geom="errorbar") + 
  stat_summary(fun.y=mean,position=position_dodge(width=0.95),geom="bar")+ ggtitle("Number of errors per block.")
```

```{r, echo = F,warning=FALSE}
ggplot(walk_smoothed, aes(x = condition, y = errors, fill=factor(exp_block_id))) +
  stat_summary(fun.data=mean_cl_normal,position=position_dodge(0.95),geom="errorbar") + 
  stat_summary(fun.y=mean,position=position_dodge(width=0.95),geom="bar")+ ggtitle("Number of errors per block - smoothed.")
```