#[sub id 1]	dv (block 1)	dv (block 2)	dv (block 3)	dv (block 4)	dv (block 5)	dv (block 6)	condition dummy code (0/1/2/3/etc)
#[sub id 2]	dv (block 1)	dv (block 2)	dv (block 3)	dv (block 4)	dv (block 5)	dv (block 6)	condition dummy code (0/1/2/3/etc)
#[sub id 3]	dv (block 1)	dv (block 2)	dv (block 3)	dv (block 4)	dv (block 5)	dv (block 6)	condition dummy code (0/1/2/3/etc)
library(dplyr)
library(reshape2)
library(openxlsx)

LEVELS <- c("real-real", "real-vr", "ve-real", "vr-real", "vr-vr")

walk_all <- read.table("walk_smoothed.csv", sep=";", header = T, stringsAsFactors = F)
df_dist <- walk_all %>% group_by(id, exp_block_id, condition) %>% summarise(mean = mean(min_norm_distance, na.rm = T))
df_dist <- dcast(df_dist, id + condition ~ exp_block_id, value.var = "mean")
df_dist$id <- as.numeric(gsub("tw", "", df_dist$id))
df_dist$condition <- factor(df_dist$condition, levels = LEVELS)
df_dist$condition <- as.numeric(df_dist$condition)
wb <- createWorkbook()
addWorksheet(wb, "Sheet 1")
writeData(wb, 1, df_dist)
saveWorkbook(wb, "min_norm_dist.xlsx", overwrite = T)


df_error <- walk_all %>% group_by(id, exp_block_id, condition) %>% summarise(mean = mean(min_norm_distance, na.rm = T))
df_error <- dcast(df_error, id + condition ~ exp_block_id, value.var = "mean")
df_error$id <- as.numeric(gsub("tw", "", df_error$id))
df_error$condition <- factor(df_error$condition, levels = LEVELS)
df_error$condition <- as.numeric(df_error$condition)
wb <- createWorkbook()
addWorksheet(wb, "Sheet 1")
writeData(wb, 1, df_error)
saveWorkbook(wb, "n_errors.xlsx", overwrite = T)
